### ISSUE TITLE
About the function that converts a "lax DER"-encoded byte slice to a signature.

### ISSUE THREAD

**Issue by koushiro** [sorpaas/libsecp256k1-rs#7]
Hello, Wei Tang

I am trying to switch to this library from [secp256k1](https://crates.io/crates/secp256k1), but this library don't have the function that converts a "lax DER" -encoded byte slice to a signature (in [secp256k1](https://crates.io/crates/secp256k1), the function called Signature::from_der_lax(data: &[u8])).

Whether this function 'Signature::parse_der(p: &[u8])' in this library is a substitute for from_der_lax. If not, would you consider adding a "lax DER"-encoded related function?

Similarly, the "Signature::normalize_s(&mut self)" in  [secp256k1](https://crates.io/crates/secp256k1).

**Comment by sorpaas** [comment]
Fixed in #8. Thank you @koushiro!
